my_custom_service:
  name: "opengate Service"
  description: "This service does something custom"
  fields:
    my_param:
      name: "My Parameter"
      description: "A parameter for the service"
      required: false
      example: "example_value"
